#!/usr/bin/env python3
import datetime,json,pathlib
B=pathlib.Path(__file__).resolve().parent.parent;R=B/'candidates/wqp_activity_panel_001/r03';P=R/'private';OLD=R.parent/'r02'
def dump(p,x):p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
d=json.loads((OLD/'private/task_definition.json').read_text());c=d['conditions'];conditions={k:c[k] for k in ['scope','samples','panel','annual_support','windows','frontier']}
conditions['frontier']=conditions['frontier'].replace('Report all feasible intervals on the duration-versus-station-coverage Pareto frontier.', 'For any dataset state, define its duration-versus-station-coverage Pareto frontier as follows.')
conditions['withdrawals']='The unmodified data define the original eligible activities and the original frontier. Consider EVERY original complete eligible activity at EVERY retained mainstem station as a separate hypothetical withdrawal, including activities at stations outside the original frontier cohorts. A withdrawal removes that one OrganizationIdentifier/ActivityIdentifier and all its results. Keep the original station universe, geographic limits, date limits and all other records. Each trial starts again from the full original data; withdrawals are never cumulative. Recompute quarterly support, supported years, all interval cohorts and the GLOBAL frontier after the withdrawal. A trial is frontier-changing if its entire set of frontier designs differs from the original set. A design identity consists of start_year, end_year and the complete set of organization/station identities in its cohort. A mere change in a sample count or selected oxygen minimum without a frontier-design change does not qualify. Test activities whether or not they were an original selected minimum. Reconsider all intervals and retained stations: previously dominated designs may become frontier designs, and equal duration/coverage designs at different dates remain separate.'
conditions['selection']='For EACH frontier-changing withdrawal and EACH interval on that trial\'s recomputed frontier, define quarter as the QUARTER-OF-YEAR of the withdrawn activity\'s ActivityStartDate. Form the set of REMAINING complete eligible activities at ANY station in that post-withdrawal interval\'s own cohort, with dates inside that interval and in that quarter-of-year across its years. Count distinct organization/activity keys in that set. Select ONE activity across the entire cohort with the lowest unrounded dissolved-oxygen concentration. Break ties by earliest ActivityStartDate, then ActivityStartTime/Time in ascending local clock order (missing after known times), then MonitoringLocationIdentifier, then ActivityIdentifier, with identifiers ordered case-sensitively and lexicographically. Report that selected activity\'s own organization, station, activity ID, date, temperature, conductance and pH. Never reuse an event/count from another withdrawal, interval or the full original record. Round the four measurements only in final output, using decimal round-half-up to two decimal places.'
conditions['output']='Return one row per frontier-changing withdrawal and post-withdrawal frontier interval. The cohort_station_ids field lists that interval\'s entire post-withdrawal set of MonitoringLocationIdentifier values, sorted lexicographically and joined with semicolons; organization is USGS-TX throughout this bounded study. Sort rows by withdrawn_ActivityIdentifier lexicographically, then start_year ascending and end_year ascending. Preserve identifiers; report years and counts as integers, quarter as Q1/Q2/Q3/Q4, dates as YYYY-MM-DD, and measurements to two decimal places. If a changing withdrawal leaves no feasible interval, output one sentinel row for it: start_year=end_year=cohort_station_count=eligible_activity_count=0, cohort_station_ids=NONE, the withdrawn activity\'s quarter, selected identifiers/date=NONE and all four measurements=NA. If no withdrawal changes the frontier, output NONE. Failed or incomplete retrieval remains an unresolved limitation, not evidence of zero records.'
cols=['withdrawn_OrganizationIdentifier','withdrawn_ActivityIdentifier','withdrawn_MonitoringLocationIdentifier','withdrawn_ActivityStartDate','start_year','end_year','cohort_station_count','cohort_station_ids','quarter','eligible_activity_count','selected_OrganizationIdentifier','selected_MonitoringLocationIdentifier','selected_ActivityIdentifier','selected_ActivityStartDate','dissolved_oxygen_mg_L','temperature_deg_C','specific_conductance_uS_cm','pH']
intro='I am auditing whether a common-observation-period comparison of seasonal low-oxygen events on the Trinity River depends on a single sampled activity. I need every individual activity withdrawal that changes the globally non-dominated continuous-period/station-cohort designs, and the surviving designs\' lowest-oxygen reference events in the season of the withdrawn observation. These are independent hypothetical data-quality sensitivity trials; they do not assert that any official observation is wrong or has actually been withdrawn, and they are not causal or flow-adjusted trend estimates.'
fmt='Return data rows only, newline-separated and pipe-separated, in this exact column order: '+'|'.join(cols)+'. Apply all stated scenario identity, cohort membership, date/quarter, units, precision, sentinel and sorting rules. Output NONE only when there is no frontier-changing withdrawal.'
labels=['Enumerate the complete mainstem universe.','Resolve source activity identities and sampling conditions.','Construct usable same-activity parameter panels.','Determine complete station-years.','Enumerate original common windows and full cohorts.','Compute the original global frontier.','Withdraw each eligible activity independently and recompute the full design state.','For each changing trial, return to its surviving intervals and select the correct seasonal event.','Write all changing-trial/interval entities.']
public={'cg':{'instruction':intro+'\n\n'+'\n\n'.join(f'{i}. {label} {v}' for i,(label,v) in enumerate(zip(labels,conditions.values()),1)),'output_format':fmt},'go':{'instruction':intro+'\n\nThe sensitivity audit must satisfy the following definitions and reporting requirements.\n\n'+'\n\n'.join(conditions.values()),'output_format':fmt}}
for v,t in public.items():dump(R/'public'/f'{v}.json',t);(R/'public'/f'{v}.md').write_text(t['instruction']+'\n\n'+fmt+'\n')
definition={'recorded_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'organization':d['organization'],'years':d['years'],'hucs':d['hucs'],'conditions':conditions,'columns':cols,'initial_state_columns':d['columns'],'output_format':fmt,'definition_before_r03_solves':True,'research_design':'Independent single-activity withdrawal sensitivity of common-period monitoring designs, using unchanged real records; no altered source facts.'};dump(P/'task_definition.json',definition)
rules=json.loads((OLD/'private/scoring_rules.json').read_text());rules.update(columns=cols,row_key=['withdrawn_OrganizationIdentifier','withdrawn_ActivityIdentifier','start_year','end_year'],sorting='withdrawn activity ID, start year, end year; P.O.A. on complete scenario/interval identities; fewer2common=>0')
rules['fields']['cohort_station_ids']={'type':'id_list','semantics':'Compare the membership set; semicolon/comma/whitespace separators and member order are presentation equivalents. Preserve individual identifiers. Repeated identical members do not add membership.'};rules['sentinels']='Declared empty-post-frontier sentinel is meaningful missing data; NONE/NA exactly as public task. Actual source recomputation determines whether any exists.';dump(P/'scoring_rules.json',rules)
dump(P/'pair_alignment.json',{'same_output_format':True,'predicate_alignment':[{'predicate':k,'CG_verbatim':v,'GO_verbatim':v,'identical_required_semantics':True,'CG_step':i} for i,(k,v) in enumerate(conditions.items(),1)],'difference':'CG adds explicit operations; GO includes every required scope, original-state/withdrawal definition, full frontier equality, trial reset, conditional quarter/event selection and reporting rule. No prior scores or oracle cardinality passed to solvers.'})
g=json.loads((OLD/'private/state_graph.json').read_text());g['nodes']=['original_station_universe','original_activity_panels','original_year_support','original_all_interval_frontier','independent_withdrawal_identity','post_withdrawal_year_support','post_withdrawal_all_interval_frontier','full_design_set_change_test','post_trial_interval_cohort_and_withdrawn_season','remaining_cohort_event_minimum','same_activity_companion_measurements','scenario_specific_sorted_output'];g['edges']=[{'from':x,'to':y} for x,y in zip(g['nodes'],g['nodes'][1:])];g['required_state_retention']='Restore the complete original record between trials. Each withdrawal changes its own support state, global frontier, cohort, year range and season-specific candidate events. Do not reuse original frontier intervals or minimum events as the universe of post-withdrawal choices.';g['retrieval_limit']='Legal complete exports may make this entirely local computation. No unavoidable adaptive network sequence is claimed. All added dependencies need real counterfactual effects and independent empirical difficulty tests.';dump(P/'state_graph.json',g)
candidate=json.loads((OLD/'candidate.json').read_text());candidate.update(revision=3,status='reference_ready',research_goal=intro,structural_upgrade='Full independent single-activity withdrawal states can reactivate previously dominated windows and tied designs; each changed global frontier sets its own cohort, dates and withdrawn quarter for selecting a remaining low-oxygen event. A local implementation is allowed; hardness remains an empirical question.',public=public)
candidate['private'].update(candidate_scope=conditions['scope'],predicates=list(conditions.values()),output_columns=cols,row_key=rules['row_key'],sorting_rules=[conditions['selection'],conditions['output']],missing_value_rules=[conditions['panel'],conditions['annual_support'],conditions['output']]);candidate['validation']={'content':'not_run','difficulty':'not_run','human_validation':'not_performed','report_paths':[]};dump(R/'candidate.json',candidate)
print('Generated final permitted revisionr03 public pair and shared scoring semantics before fresh solves')
