#!/usr/bin/env python3
import datetime as dt,json,pathlib
ROOT=pathlib.Path(__file__).resolve().parents[3]
REV=ROOT/'construction_pipeline/wqp_single/candidates/wqp_activity_panel_001/r01'
P=REV/'private'
def dump(p,x):p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
conditions={
'scope':'Use the Water Quality Portal legacy WQX 2.2 records for organization USGS-TX and calendar year 2019 (ActivityStartDate from 2019-01-01 through 2019-12-31 inclusive). The candidate universe is all monitoring locations with any recorded data in that year in HUC8 12030202 or 12030203. Retain mainstem locations whose MonitoringLocationName starts with "Trinity Rv " and whose MonitoringLocationTypeName is exactly "Stream" or "Stream: Tidal stream"; this study includes the tidal mainstem but excludes other named rivers, tributaries and reservoirs.',
'samples':'An eligible activity must have ActivityMediaName exactly "Water" and ActivityTypeCode exactly "Sample-Routine". Exclude quality-control field replicates and all other activity types, including "Unknown". Identify activities by the combination of OrganizationIdentifier and ActivityIdentifier, and verify the MonitoringLocationIdentifier and ActivityStartDate agree when linking result and activity records. An activity is the recorded sampling unit, not an entire station visit: do not merge different activities merely because they share a station, date, time or depth. Preserve reported depth as metadata; blank depth is unknown and does not imply surface water. Use ActivityStartDate, not digits in ActivityIdentifier, to determine the calendar quarter.',
'panel':'A complete activity must contain all four USGS parameter codes: 00010 (water temperature), 00095 (specific conductance at 25 degrees C), 00300 (dissolved-oxygen concentration), and 00400 (pH). Oxygen percent saturation, including code 00301, is not a substitute for code 00300. Use only finite numeric results marked Accepted or Final, with ResultValueTypeName "Actual", and with both ResultDetectionConditionText and MeasureQualifierCode blank. Discard results with missing or incompatible units. Normalize temperature to degrees C (degrees F: (F-32)*5/9), conductance to microSiemens/cm at 25 degrees C (microSiemens/cm and micromhos/cm are equivalent; milliSiemens/cm multiply by 1000), dissolved oxygen to mg/L (micrograms/L divide by 1000), and pH to standard units. Within each activity and parameter code, the usable results must yield exactly one distinct normalized numeric value; repeated identical values count once, but conflicting values make that activity incomplete. Do not choose an arbitrary first value or average conflicts.',
'coverage':'A station qualifies only if it has at least one complete eligible activity in each of the four calendar quarters January-March, April-June, July-September and October-December 2019. Presence of each parameter somewhere in the station-year, or a period-of-record envelope, is insufficient. Count distinct eligible organization/activity keys within each station-quarter.',
'selection':'For each qualifying station and each quarter, select the complete eligible activity with the lowest unrounded dissolved-oxygen concentration. Break ties by earliest ActivityStartDate, then the reported ActivityStartTime/Time in ascending local clock order (missing times after known times), then ActivityIdentifier in case-sensitive lexicographic order. Report the water temperature, specific conductance and pH from that selected activity, not independent minima or values from other activities. Round these four measurements only for final output to two decimal places, using decimal round-half-up.',
'output':'Output one row per qualifying station-quarter, sorted by MonitoringLocationIdentifier in ascending lexicographic order and then by quarter Q1 through Q4. Preserve source identifiers and the eight-digit HUC as strings. Use an ISO YYYY-MM-DD activity date, quarter labels 2019-Q1 through 2019-Q4, an integer activity count, and two decimal places for the four measurements. If no station qualifies, output NONE. A failed or incomplete data retrieval is an unresolved limitation, not evidence of zero qualifying activities.'}
fmt='Return data rows only, separated by newlines, with these pipe-separated columns in this exact order: OrganizationIdentifier|MonitoringLocationIdentifier|HUC|quarter|eligible_activity_count|ActivityIdentifier|ActivityStartDate|dissolved_oxygen_mg_L|temperature_deg_C|specific_conductance_uS_cm|pH. Use the units, precision, identity, missing-data and sorting rules stated in the task. Output NONE if the qualifying set is empty.'
intro='I am building a seasonal reference panel for low-dissolved-oxygen sampling events on the lower Trinity River. I need stations with comparable routine samples in every quarter of 2019, and the accompanying water-quality measurements from each quarter\'s lowest-oxygen eligible activity.'
labels=['Enumerate the bounded station universe.','Check the recorded activity identity and sampling conditions.','Build the complete four-parameter activities.','Reassess station eligibility across the full year.','Select the quarterly low-oxygen activity and attach its own measurements.','Produce the final ordered table.']
cg=intro+'\n\n'+'\n\n'.join(f'{i}. {label} {text}' for i,(label,text) in enumerate(zip(labels,conditions.values()),1))
go=intro+'\n\nThe reference panel must satisfy the following data definition and reporting requirements.\n\n'+'\n\n'.join(conditions.values())
public={'cg':{'instruction':cg,'output_format':fmt},'go':{'instruction':go,'output_format':fmt}}
for v,t in public.items():dump(REV/'public'/f'{v}.json',t);(REV/'public'/f'{v}.md').write_text(t['instruction']+'\n\n'+fmt+'\n')
dump(P/'task_definition.json',{'organization':'USGS-TX','year':2019,'hucs':['12030202','12030203'],'conditions':conditions,'output_format':fmt,'scope_history':'exploration_decisions.md','created_before_content_solves':True})
dump(P/'pair_alignment.json',{'same_output_format':True,'predicate_alignment':[{'predicate':key,'CG_verbatim':text,'GO_verbatim':text,'identical_required_semantics':True,'CG_step':i} for i,(key,text) in enumerate(conditions.items(),1)],'differences':'CG adds explicit executable stage labels. GO states the same required definitions as a research specification without stage labels. No answer IDs, expected cardinality, oracle, start URL, private metadata, or prior solves supplied.','language_review':'English task text; exact parameter codes are required to distinguish concentration/saturation and matched measurements. Dataset version/source name is necessary to disambiguate WQP legacy/beta coverage; no direct query URL supplied.'})
cols=['OrganizationIdentifier','MonitoringLocationIdentifier','HUC','quarter','eligible_activity_count','ActivityIdentifier','ActivityStartDate','dissolved_oxygen_mg_L','temperature_deg_C','specific_conductance_uS_cm','pH']
fields={'eligible_activity_count':{'type':'integer'},'dissolved_oxygen_mg_L':{'type':'decimal','units':{'mg/L':{},'mg/l':{},'ug/L':{'scale_den':1000},'µg/L':{'scale_den':1000}}},'temperature_deg_C':{'type':'decimal','units':{'deg C':{},'°C':{},'deg F':{'offset':32,'scale_num':5,'scale_den':9},'°F':{'offset':32,'scale_num':5,'scale_den':9}}},'specific_conductance_uS_cm':{'type':'decimal','units':{'uS/cm':{},'µS/cm':{},'uS/cm @25C':{},'umho/cm':{},'mS/cm':{'scale_num':1000}}},'pH':{'type':'decimal','units':{'std units':{},'SU':{}}}}
dump(P/'scoring_rules.json',{'status':'deterministic_explicit','columns':cols,'row_key':['OrganizationIdentifier','MonitoringLocationIdentifier','quarter'],'fields':fields,'precision':'Round source computations HALF_UP to 2dp; compare predicted decimals exactly without further rounding or tolerance. Equivalent trailing zeros/explicit equivalent units allowed.','duplicates':'First occurrence eligible for credit; all duplicate rows count in denominator, no extra reward.','sorting':'station ascending then quarter; P.O.A. shared composite keys, no prediction reorder; fewer than2 =>0','missing':'Blank/absent output values incorrect; missing rows penalized; NONE parsed as empty; nonempty unparsable unscored and reported.'})
sources=[]
for file in sorted((P/'sources').glob('*.json')):
 d=json.loads(file.read_text());sources.append({'source_id':d['source_id'],'url':d['url'],'method':d['method'],'parameters':d['parameters'],'requested_at':d['requested_at'],'received_at':d['received_at'],'status':d['receipt'].get('http_code'),'complete':d['complete'],'content_type':d['receipt'].get('content_type'),'response_path':'private/sources/'+d['saved_file'],'request_receipt_path':'private/sources/'+file.name,'headers_path':'private/sources/'+file.stem+'.headers','data_version':'WQP legacy WQX2.2 current retrieval of fixed historical2019 slice' if '2019' in file.stem else 'Current official documentation/detail or exploratory response; see exact parameters','locator':'CSV record ordinal including header=1 plus compound keys; HTML element/table or text label'})
dump(P/'source_manifest.json',sources)
graph={'default_state':{'source_id':'detail_USGS-08066000','visible':'station metadata and characteristic-group period envelopes; no routine-sample quarter panel or selected activity measurements'},'target_state':{'sources':['usgs_station_2019_lower_trinity','usgs_activity_2019_lower_trinity','usgs_narrow_2019_lower_trinity_panel'],'visible':'complete bounded station set; activities with sample type/date/depth; keyed parameter result values'},'nodes':['station_universe','activity_and_parameter_records','complete_routine_panels','quarter_coverage','qualifying_stations','minimum_DO_activity','same_activity_other_measurements','sorted_output'],'edges':[{'from':a,'to':b,'type':typ,'effect':effect} for a,b,typ,effect in [('station_universe','activity_and_parameter_records','data','Retain organisation and candidate location scope; broad export can be prefetched.'),('activity_and_parameter_records','complete_routine_panels','data','Join within organisation/activity; discard QC/Unknown and incomplete/conflicting panels.'),('complete_routine_panels','quarter_coverage','data','Count only eligible activities in actual calendar quarters.'),('quarter_coverage','qualifying_stations','control','Absence of any quarter rejects the station despite annual indicator presence.'),('qualifying_stations','minimum_DO_activity','control','Only retained stations produce quarterly minima.'),('minimum_DO_activity','same_activity_other_measurements','data','Selected ID determines which temperature/conductance/pH attach.'),('same_activity_other_measurements','sorted_output','data','Output station-quarter entities, not activity-ID-only ordering.')]],'retrieval_necessity':'Not established. All fields may be prefetched with bounded official bulk exports; graph edges above are calculation/filtering dependencies, not a claim of unavoidable adaptive network requests. Independent blind shortcut attempts must decide benchmark suitability.'}
dump(P/'state_graph.json',graph)
c={'candidate_id':'wqp_activity_panel_001','revision':1,'ecosystem':'WATER_QUALITY_PORTAL','domain':'WATER_QUALITY_PORTAL','status':'reference_ready','old_task_refs':['waterquality_004'],'research_goal':intro,'structural_upgrade':'Quarterly eligibility is determined by routine Water activities with jointly usable coded parameters; quarterly minimum DO selects the identity for attached measurements. Annual presence, QC inclusion and independent extrema produce real counterfactual differences. Adaptive retrieval necessity remains unproven.','public':public,'private':{'source_version':'WQP legacy WQX2.2, retrieved2026-09-08; calendar2019; saved raw responses','start_urls':['https://www.waterqualitydata.us/'],'candidate_scope':conditions['scope'],'predicates':list(conditions.values()),'output_columns':cols,'row_key':['OrganizationIdentifier','MonitoringLocationIdentifier','quarter'],'sorting_rules':[conditions['selection'],conditions['output']],'missing_value_rules':[conditions['panel'],conditions['output']],'source_manifest_path':'private/source_manifest.json','state_graph_path':'private/state_graph.json','oracle_path':'private/reference/oracle.psv','reference_script_path':'private/reference/solve_reference.py'},'validation':{'content':'not_run','difficulty':'not_run','human_validation':'not_performed','report_paths':[]}}
dump(REV/'candidate.json',c)
print('Wrote candidate, public pair, alignment, source manifest and explicit scoring rules before content solves.')
