#!/usr/bin/env python3
"""Generate r02's paired public tasks from one complete semantic definition."""
import datetime as dt,json,pathlib,shutil
B=pathlib.Path(__file__).resolve().parent.parent;REV=B/'candidates/wqp_activity_panel_001/r02';P=REV/'private';OLD=REV.parent/'r01'
def dump(p,x):p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
old=json.loads((OLD/'private/task_definition.json').read_text());hucs=[f'120301{i:02d}' for i in range(1,10)]+[f'120302{i:02d}' for i in range(1,4)]
conditions={
'scope':'Use the Water Quality Portal legacy WQX 2.2 records for organization USGS-TX, with ActivityStartDate from 2000-01-01 through 2019-12-31 inclusive. The finite station universe is all monitoring locations with any recorded data in this period in HUC8 '+', '.join(hucs)+'. Retain locations whose MonitoringLocationName starts with "Trinity Rv " and whose MonitoringLocationTypeName is exactly "Stream" or "Stream: Tidal stream". The tidal mainstem is included; other named rivers, tributaries, reservoirs and wells are outside this study.',
'samples':old['conditions']['samples'],
'panel':old['conditions']['panel'],
'annual_support':'A station supports a calendar year only when it has at least one complete eligible activity in each of that year\'s four calendar quarters: January-March, April-June, July-September, October-December. Indicator presence somewhere in a year, four samples in one season, and period-of-record envelopes do not establish this condition. Years with a missing quarter remain gaps; do not fill them or bridge them.',
'windows':'Consider every inclusive contiguous calendar-year interval [start_year, end_year] within 2000–2019, including one-year intervals. For each interval its cohort is exactly ALL retained stations that support EVERY year in that interval. This is a fixed membership set over the whole interval, not a union of annually changing stations and not a chosen subset. An interval is feasible only if its cohort contains at least two stations, so there is a between-station comparison. Its duration is end_year-start_year+1 and its coverage is the number of stations in its cohort.',
'frontier':'Report all feasible intervals on the duration-versus-station-coverage Pareto frontier. Interval X dominates interval Y if X has at least as many years AND at least as many cohort stations as Y, with at least one of these two quantities strictly larger. Compare against ALL feasible intervals, including intervals at different dates or with different or overlapping cohorts. Retain an interval only if no feasible interval dominates it. Equal duration and coverage do not dominate one another: retain all such tied intervals when undominated. Do not choose one longest interval, apply a weighted score, require containment, or treat equal station counts as equal membership.',
'selection':'For EACH retained frontier interval, EACH station in that interval\'s own cohort, and EACH quarter-of-year Q1, Q2, Q3, Q4, use only complete eligible activities at that station with ActivityStartDate inside that interval and in that quarter-of-year across its years. Count distinct organization/activity keys in this set and select the activity with the lowest UNROUNDED dissolved-oxygen concentration. Break ties by earliest ActivityStartDate, then ActivityStartTime/Time in ascending local clock order (missing times after known times), then ActivityIdentifier in case-sensitive lexicographic order. Attach temperature, specific conductance and pH from this selected activity itself. A station appearing in several intervals must be recomputed separately for each interval; do not reuse its minimum or count from a different interval or the full 2000–2019 record. Round the four measurements only for final output, to two decimal places using decimal round-half-up.',
'output':'Output one row per retained interval, cohort station and quarter-of-year. Sort by start_year ascending, end_year ascending, MonitoringLocationIdentifier ascending lexicographically, then Q1 through Q4. Report start_year, end_year, cohort_station_count and eligible_activity_count as integers; preserve organization/location IDs and eight-digit HUC as strings; use YYYY-MM-DD dates and two decimal places for measurements. Output NONE if no feasible interval exists. Incomplete retrieval is an unresolved limitation, not evidence of missing observations or zero support.'}
cols=['start_year','end_year','cohort_station_count','OrganizationIdentifier','MonitoringLocationIdentifier','HUC','quarter','eligible_activity_count','ActivityIdentifier','ActivityStartDate','dissolved_oxygen_mg_L','temperature_deg_C','specific_conductance_uS_cm','pH']
fmt='Return data rows only, separated by newlines, with these pipe-separated columns in this exact order: '+'|'.join(cols)+'. Apply the stated identity, units, precision, interval membership and sorting rules. Output NONE if the feasible set is empty.'
intro='I am designing a common-observation-period comparison of seasonal low-oxygen sampling events on the Trinity River. Longer records and more monitoring stations are competing design goals. I need every non-dominated combination of a continuous year interval and its full eligible station cohort, together with each cohort station\'s seasonal low-oxygen reference panel within that same interval. This describes observed sampling support and recorded events; it is not a causal or flow-adjusted trend estimate.'
labels=['Enumerate the bounded mainstem station universe.','Resolve activity identity and sampling eligibility.','Construct complete same-activity four-parameter panels.','Build each station\'s exact supported-year set.','Enumerate common continuous windows and their full cohorts.','Compare all feasible windows and retain the frontier.','Return to each retained window and select its own seasonal events.','Write the complete ordered table.']
public={'cg':{'instruction':intro+'\n\n'+'\n\n'.join(f'{i}. {label} {v}' for i,(label,v) in enumerate(zip(labels,conditions.values()),1)),'output_format':fmt},'go':{'instruction':intro+'\n\nThe comparison must satisfy these definitions and reporting requirements.\n\n'+'\n\n'.join(conditions.values()),'output_format':fmt}}
for v,t in public.items():dump(REV/'public'/f'{v}.json',t);(REV/'public'/f'{v}.md').write_text(t['instruction']+'\n\n'+fmt+'\n')
dump(P/'task_definition.json',{'recorded_at':dt.datetime.now(dt.timezone.utc).isoformat(),'organization':'USGS-TX','years':[2000,2019],'hucs':hucs,'conditions':conditions,'columns':cols,'output_format':fmt,'definition_before_r02_solves':True})
dump(P/'pair_alignment.json',{'same_output_format':True,'predicate_alignment':[{'predicate':k,'CG_verbatim':v,'GO_verbatim':v,'identical_required_semantics':True,'CG_step':i} for i,(k,v) in enumerate(conditions.items(),1)],'differences':'Only CG adds operational step labels. GO preserves every answer-determining condition, complete frontier definition and reporting rule. No answer cardinality or candidate identifiers in payload.'})
rules=json.loads((OLD/'private/scoring_rules.json').read_text());rules.update(columns=cols,row_key=['start_year','end_year','OrganizationIdentifier','MonitoringLocationIdentifier','quarter'],sorting='start_year, end_year, station identifier, quarter; P.O.A. on composite entity keys; <2 common keys =>0')
for f in ['start_year','end_year','cohort_station_count']:rules['fields'][f]={'type':'integer'}
dump(P/'scoring_rules.json',rules)
for stem in ['services','userguide','epa_definitions']:
 for suffix in ['.response','.json','.headers']:
  dest=P/'sources'/(stem+suffix)
  if not dest.exists():shutil.copyfile(OLD/'private/sources'/(stem+suffix),dest)
sources=[]
for f in sorted((P/'sources').glob('*.json')):
 d=json.loads(f.read_text())
 if 'source_id' not in d:continue
 sources.append({'source_id':d['source_id'],'url':d['url'],'parameters':d['parameters'],'requested_at':d['requested_at'],'received_at':d['received_at'],'http_status':d['receipt'].get('http_code'),'transport_complete':d['complete'],'valid_data_response':d['complete'] and d['receipt'].get('http_code')==200,'response_path':'private/sources/'+d['saved_file'],'receipt_path':'private/sources/'+f.name,'headers_path':'private/sources/'+f.stem+'.headers'})
dump(P/'source_manifest.json',sources)
dump(P/'state_graph.json',{'nodes':['unfiltered_station_universe','mainstem_scope','activity_identity_and_usable_parameter_values','station_quarter_support','station_year_support','interval_cohorts','global_duration_coverage_frontier','window_specific_seasonal_minimum','same_activity_companion_values','all_sorted_entities'],'edges':[{'from':a,'to':b} for a,b in zip(['unfiltered_station_universe','mainstem_scope','activity_identity_and_usable_parameter_values','station_quarter_support','station_year_support','interval_cohorts','global_duration_coverage_frontier','window_specific_seasonal_minimum','same_activity_companion_values'],['mainstem_scope','activity_identity_and_usable_parameter_values','station_quarter_support','station_year_support','interval_cohorts','global_duration_coverage_frontier','window_specific_seasonal_minimum','same_activity_companion_values','all_sorted_entities'])],'required_state_retention':'Each interval has its own exact cohort and its own seasonal event search range. Global frontier comparison spans all feasible intervals, not merely nested intervals.','retrieval_limit':'Bounded official bulk exports are legal and may move these operations entirely into local computation; no unavoidable adaptive HTTP sequence is claimed. Difficulty requires new empirical results, not graph length.'})
c=json.loads((OLD/'candidate.json').read_text());c.update(revision=2,status='reference_ready',research_goal=intro,structural_upgrade='Activity-qualified quarterly observations determine gapped supported-year sets. Their intersections determine changing fixed cohorts for every contiguous interval. Global duration/coverage dominance selects multiple comparison designs; each design then controls its own seasonal event scope. All claimed effects require real counterfactual recomputation.',public=public)
c['private'].update(source_version='WQP legacy WQX2.2, retrieved2026-09-08, calendar2000–2019; exact original responses retained',candidate_scope=conditions['scope'],predicates=list(conditions.values()),output_columns=cols,row_key=rules['row_key'],sorting_rules=[conditions['selection'],conditions['output']],missing_value_rules=[conditions['panel'],conditions['annual_support'],conditions['output']])
c['validation']={'content':'not_run','difficulty':'not_run','human_validation':'not_performed','report_paths':[]};dump(REV/'candidate.json',c)
print('r02 paired tasks and scoring rules generated before new blind solves')
