from pathlib import Path
import json,shutil
B=Path(__file__).resolve().parent

def put(n,x):(B/n).write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
intro='Audit published attempts to reproduce the claim that a brief low-pH treatment can turn somatic cells into pluripotent STAP cells. I need the procedures actually reported by each study and the evidence supporting its conclusion about pluripotency.'
scope='Use the public European index of life-science publications and archived full text. The reference scope is its citing-publication records marked open access, observed on 13 September 2026 (UTC), for the January 2014 Nature experimental article introducing stimulus-triggered conversion of somatic cells into pluripotency. Use that original experimental article, not its retraction notice or the companion article about bidirectional developmental potential. This is an audit of that indexed open-access cohort, not every freely readable paper or all worldwide citations.'
steps='To carry out the audit:\n1. Identify the original experimental publication and its indexed open-access citing cohort.\n2. Inspect each potentially eligible paper\'s own experiments and reported methods, following the discovered full-text records where the summary is insufficient.\n3. Separate marker observations from functional evidence, then return the study table.'
eligibility='Include a citing publication only if it reports its own experimental attempt to induce STAP-like pluripotency in somatic cells by transient low-pH treatment. Include unsuccessful, partial and modified-protocol attempts, even if they stopped at marker testing. Exclude reviews, news, commentary, computational reanalysis and reports of others\' experiments unless the publication also reports its own qualifying attempt. Chronic acidic-culture studies, other chemical stresses and maintenance of existing stem cells do not qualify. Use each main article\'s observed version; peer-review comments and experiments merely cited by the article are not that study\'s results.'
claim='Record the study\'s own described procedure, including the relevant changes it reports. This is an audit of author-reported methods, not a certification that every step faithfully reproduced the original protocol. For the procedure summary, cover only the acidifying agents, use of FGF2 after treatment, CD45 sorting in the described spleen-cell preparation, and an explicitly reported difference in the Oct4-GFP reporter line from the original study. Do not list reagent amounts, durations, animal counts or every technical difference.'
procedure='Use these PROCEDURE tags when supported by the reported methods:\n- HCL or ATP: that agent was used to create the transient low-pH condition; include both if both were tested.\n- FGF2: FGF2 was included in at least one post-treatment culture condition.\n- CD45_SORTED or CD45_UNSORTED: the described spleen-cell preparation did or did not include selection of CD45-positive cells by sorting. Density separation alone is not CD45 sorting. Use CD45_UNCLEAR if this cannot be determined, or NO_SPLEEN if no spleen cells were used.\n- REPORTER_DIFFERENT: the authors explicitly identify their Oct4-GFP reporter mouse line as different from that of the original report. Do not use a constitutive lineage-tracing GFP line to decide this tag.'
markers='In MARKERS, use NEGATIVE if the reported induction assays found no convincing pluripotency-marker induction; RARE_POSITIVE if rare cells or aggregates had reported molecular marker evidence, even if preliminary or most assays were negative; POSITIVE for convincing marker induction not described as rare; UNCLEAR for an unresolved signal without supporting molecular marker evidence; or NOT_REPORTED. Green fluorescence alone is not proof of endogenous pluripotency-marker induction, and markers alone do not establish functional pluripotency.'
function='In FUNCTIONAL_EVIDENCE, report four tags for the same study\'s treated cells:\n- CHIMERA_POSITIVE or CHIMERA_NEGATIVE for observed contribution or no significant contribution after embryo injection; CHIMERA_NOT_PERFORMED if explicitly not done; CHIMERA_NOT_REPORTED if the article gives no such assay result or statement.\n- TERATOMA_POSITIVE or TERATOMA_NEGATIVE for a reported teratoma pluripotency assay; TERATOMA_NOT_PERFORMED if explicitly not done; TERATOMA_NOT_REPORTED if unstated. Tumor growth alone without differentiation evidence is not a positive teratoma pluripotency assay.\n- LINES_ESTABLISHED or LINES_FAILED for successful or unsuccessful derivation of stable secondary STAP-related stem-cell lines; LINES_NOT_ATTEMPTED if explicitly not attempted; LINES_NOT_REPORTED if unstated. Transient aggregates or short-lived colonies are not stable cell lines.\n- PLURIPOTENCY_ESTABLISHED or PLURIPOTENCY_NOT_ESTABLISHED according to whether the study establishes functional pluripotency of its induced cells under its tested conditions. Preserve the distinction between a negative assay, an explicitly unperformed assay and an unreported assay; do not convert any of these into a universal claim that induction is impossible.'
missing='Do not infer missing experiments or treat a positive control as successful induction. If a required source or the complete indexed cohort cannot be resolved, return UNRESOLVED rather than guess.'
parts=[intro,scope,eligibility,claim,procedure,markers,function,missing]
fmt='Return only a pipe-separated table with header PMID|PROCEDURE|MARKERS|FUNCTIONAL_EVIDENCE. Give one row per eligible publication, sorted by numeric PMID ascending. PROCEDURE is the set of applicable tags above, separated by semicolons; MARKERS is one tag; FUNCTIONAL_EVIDENCE contains one CHIMERA tag, one TERATOMA tag, one LINES tag and one PLURIPOTENCY tag. Tag order within a cell does not matter. Use the numeric publication identifier, not a full-text archive identifier. If no publication qualifies, return NONE without a header. If required evidence is unresolved, return UNRESOLVED without a header.'
go={'instruction':'\n\n'.join(parts),'output_format':fmt};cg={'instruction':'\n\n'.join(parts[:2]+[steps]+parts[2:]),'output_format':fmt}
put('cg.json',cg);put('go.json',go)
put('pair_alignment.json',{'CG_only_guidance':steps,'predicates':[{'id':k,'cg_quote':v,'go_quote':v} for k,v in zip(['goal','source_scope','eligibility','reported_method_claim','procedure_fields','markers','functional_evidence','missing'],parts)],'output_format_shared':True,'ambiguity_challenges':[{'readings':'All worldwide free citing papers vs the stated indexed OPEN_ACCESS cohort','resolution':scope},{'readings':'Only successful or exact-protocol reproductions vs own attempted transient induction','resolution':eligibility+' '+claim},{'readings':'Peer review experiments or cited Niwa results vs own main-article findings','resolution':eligibility},{'readings':'Negative vs unperformed vs unreported','resolution':function}],'constructor_review_only':True})
c={'candidate_id':'stap_replication_protocol_001','revision':1,'ecosystem':'Europe PMC','domain':'STEM_CELL_REPLICATION_EVIDENCE','status':'reference_ready','old_task_refs':['epmc_quantitative_001/r02','epmc_long_term_harms_001'],'research_goal':intro,'structural_upgrade':'Original-article identity selects specialized reverse-citation and open-access scope; discovered full-text identities expose own-protocol and marker/function distinctions missing from complete core records. Different scientific need from issue-count corrections or long-term-harms review tracing; no difficulty superiority asserted.','public':{'cg':cg,'go':go},'private':{'source_version':'Indexed cohort observed 2026-09-13 UTC; main-article versions in scope_checks.json; runtime date remains 2026-09-09.','start_urls':['https://europepmc.org/'],'candidate_scope':scope,'predicates':parts[2:],'output_columns':['PMID','PROCEDURE','MARKERS','FUNCTIONAL_EVIDENCE'],'row_key':['PMID'],'sorting_rules':['Numeric PMID ascending; order within tag sets irrelevant.'],'missing_value_rules':['Explicitly not performed is distinct from unreported; unresolved required source yields UNRESOLVED; verified empty eligibility yields NONE.'],'source_manifest_path':'source_manifest.json','state_graph_path':'state_graph.json','oracle_path':'oracle.psv','reference_script_path':'reference.py'},'validation':{'content':'not_run','difficulty':'not_run','human_validation':'not_performed','report_paths':['construction_report.md','execution_checks.json','pair_alignment.json','source_stability.json','protocol_claim_decision.json']}}
put('candidate.json',c)
r={'columns':c['private']['output_columns'],'row_key':['PMID'],'fields':{'PMID':{'type':'string'},'PROCEDURE':{'type':'id_list','uppercase':True,'aliases':{}},'MARKERS':{'type':'string','uppercase':True,'aliases':{'rare positive':'RARE_POSITIVE','Rare positive':'RARE_POSITIVE','rare-positive':'RARE_POSITIVE','negative':'NEGATIVE'}},'FUNCTIONAL_EVIDENCE':{'type':'id_list','uppercase':True,'aliases':{}}}}
put('rules.json',r)
shutil.copyfile(B/'rebuilt/oracle.psv',B/'oracle.psv');shutil.copyfile(B/'rebuilt/scope_checks.json',B/'scope_checks.json');shutil.copyfile(B/'rebuilt/inventory.json',B/'inventory.json')
put('state_graph.json',{'nodes':[{'id':'S0','state':'default literature search','evidence':'No complete scoped study set or method/function table'},{'id':'S1','state':'original experimental article search','evidence':'PMID 24476887 MED versus retraction 24990753'},{'id':'S2','state':'CITES:<discovered original>_MED AND OPEN_ACCESS:Y; full core results','evidence':'49 PMIDs/PMCIDs and abstracts; 7 lack abstracts'},{'id':'S3','state':'discovered PMCID fullTextXML/main-article body','evidence':'own procedures, rare marker evidence, functional tests and explicit not-done statements'},{'id':'S4','state':'evidence-grounded eligible study table','evidence':'3 eligible studies; 46 exclusions'}],'edges':[{'from':'S1','to':'S2','type':'control','field':'original experimental PMID/source determines reverse-citation query'},{'from':'S2','to':'S3','type':'control','field':'discovered PMCID identities and unresolved eligibility/functional claims determine full-text retrieval'},{'from':'S3','to':'S4','type':'data','field':'own-study evidence determines eligibility, procedure and marker/function classifications'}],'actual_witnesses':['Niwa abstract does not give ATP/FGF2, rare markers, or failed stable-line derivation; full core is insufficient for required fields.','Aizawa full text explicitly separates unperformed teratoma/line tests from negative chimera assay; nested peer reviews are separate.','Som chronic acid marker study excluded after its own methods clarify time-course meaning.'],'limitations':'API result-driven batch retrieval is a legitimate execution of this dependency. Unknown fixed-packet coverage is not a demonstrated bypass. Universal shortcut resistance and model difficulty not validated.'})
print('pair, candidate and rules written')
